name: affiliate-service
project: mintyn-project
namespace: sandbox
values: |-
  fullnameOverride: affiliate-service
  image: 
    repository: mintfintech/mint-affiliate-service:app-3
  namespace: sandbox
  containerPort: 8101
  autoscaling:
    enabled: false
  role:
    enabled: true
  ingress:
    host: affiliate-service
    domain: mintfintech.com
  resources:
    requests:
      memory: "200Mi"
      cpu: "30m"
    limits:
      memory: "1Gi"
      cpu: "500m"
  lProbe:
    enabled: true
    path: /actuator/health
    failureThreshold: 5
    periodSeconds: 10
    initialDelaySeconds: 60
  rProbe:
    enabled: true
    path: /actuator/health
    failureThreshold: 5
    periodSeconds: 10
    initialDelaySeconds: 60
  env:
    - name: AFFILIATE_SERVICE_SERVICE_HOST
      value: http://affiliate-service
    - name: KUBERNETES_NAMESPACE
      value: sandbox
    - name: KAFKA_BROKERS_URL
      valueFrom:
        configMapKeyRef:
          name: configs
          key: KAFKA_HOST
  volumeMounts:
    - name: config
      mountPath: "/config"
      readOnly: true
  volumes:
    - name: config
      configMap:
        name: affiliate-service
