name: core-banking-service
project: mintyn-project
namespace: sandbox
values: |-
  fullnameOverride: core-banking-service
  image: 
    repository: mintfintech/mint-core-banking-service:app-31
  namespace: sandbox
  containerPort: 8092
  autoscaling:
    enabled: false
  role:
    enabled: true
  ingress:
    host: core-banking-service
    domain: mintfintech.com
  resources:
    requests:
      memory: "450Mi"
      cpu: "100m"
    limits:
      memory: "600Mi"
      cpu: "500m"
  lProbe:
    enabled: true
    path: /actuator/health
    failureThreshold: 5
    periodSeconds: 10
    initialDelaySeconds: 60
  rProbe:
    enabled: true
    path: /actuator/health
    failureThreshold: 5
    periodSeconds: 10
    initialDelaySeconds: 60
  envFrom:
    - secretRef:
        name: core-banking-service
  env:
    - name: CORE_BANKING_SERVICE_SERVICE_HOST
      value: http://core-banking-service
    - name: KUBERNETES_NAMESPACE
      value: sandbox
    - name: SPRING_PROFILES_ACTIVE
      value: sandbox
    - name: KAFKA_BROKERS_URL
      valueFrom:
        configMapKeyRef:
          name: configs
          key: KAFKA_HOST
  volumeMounts:
    - name: config
      mountPath: "/config"
      readOnly: true
  volumes:
    - name: config
      configMap:
        name: core-banking-service
