name: investplus-app
project: mintyn-project
namespace: sandbox
values: |-
  fullnameOverride: investplus-app
  image: 
    repository: mintfintech/investplus-app:app-23
  namespace: sandbox
  containerPort: 3000
  autoscaling:
    enabled: false
  role:
    enabled: true
  ingress:
    host: investplus-sandbox
    domain: mintyn.com
  resources:
    requests:
      memory: "10Mi"
      cpu: "10m"
    limits:
      memory: "200Mi"
      cpu: "100m"
  lProbe:
    enabled: true
    path: /
    failureThreshold: 5
    periodSeconds: 5
    initialDelaySeconds: 10
  rProbe:
    enabled: false
    path: /
    failureThreshold: 5
    periodSeconds: 5
    initialDelaySeconds: 10
