name: merchant-trade-portal
project: mintyn-project
namespace: sandbox
values: |-
  fullnameOverride: merchant-trade-portal
  image: 
    repository: mintfintech/merchant-trade-portal:app-41
  namespace: sandbox
  containerPort: 3000
  autoscaling:
    enabled: false
  role:
    enabled: true
  ingress:
    host: merchant-marketplace-sandbox
    domain: mintyn.com
  resources:
    requests:
      memory: "10Mi"
      cpu: "10m"
    limits:
      memory: "300Mi"
      cpu: "200m"
  lProbe:
    enabled: true
    path: /
    failureThreshold: 5
    periodSeconds: 5
    initialDelaySeconds: 10
  rProbe:
    enabled: false
    path: /
    failureThreshold: 5
    periodSeconds: 5
    initialDelaySeconds: 10
