name: trade-portal
project: mintyn-project
namespace: sandbox
values: |-
  fullnameOverride: trade-portal
  image: 
    repository: mintfintech/mintyn-trade-portal:app-3
  namespace: sandbox
  containerPort: 80
  autoscaling:
    enabled: false
  role:
    enabled: true
  ingress:
    host: tradeportal-sandbox
    domain: mintyn.com
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "2Gi"
      cpu: "1000m"
  lProbe:
    enabled: false
    path: /
    failureThreshold: 5
    periodSeconds: 5
    initialDelaySeconds: 10
  rProbe:
    enabled: false
    path: /
    failureThreshold: 5
    periodSeconds: 5
    initialDelaySeconds: 10
