name: affiliate-webapp
project: mintyn-project
namespace: sandbox
values: |-
  fullnameOverride: affiliate-webapp
  image: 
    repository: mintfintech/mint-affiliate-app:app-7
  namespace: sandbox
  containerPort: 80
  autoscaling:
    enabled: false
  role:
    enabled: true
  ingress:
    host: affiliate-sandbox
    domain: mintyn.com
  resources:
    requests:
      memory: "10Mi"
      cpu: "10m"
    limits:
      memory: "2Gi"
      cpu: "1000m"
  lProbe:
    enabled: false
    path: /
    failureThreshold: 5
    periodSeconds: 5
    initialDelaySeconds: 10
  rProbe:
    enabled: false
    path: /
    failureThreshold: 5
    periodSeconds: 5
    initialDelaySeconds: 10
