name: quays-insurance-service-ai
project: mintyn-project
namespace: sandbox
values: |-
  fullnameOverride: quays-insurance-service-ai
  image: 
    repository: goquays/quays-insurance-service-ai:app-12
  namespace: sandbox
  containerPort: 5000
  autoscaling:
    enabled: false
  role:
    enabled: true
  ingress:
    host: quays-insurance-ai
    domain: mintfintech.com
  resources:
    requests:
      memory: "500Mi"
      cpu: "200m"
    limits:
      memory: "1Gi"
      cpu: "1000m"
  lProbe:
    enabled: false
    path: /health
    failureThreshold: 5
    periodSeconds: 10
    initialDelaySeconds: 60
  rProbe:
    enabled: false
    path: /health
    failureThreshold: 5
    periodSeconds: 10
    initialDelaySeconds: 60
  env:
    - name: QUAYS_INSURANCE_SERVICE_SERVICE_AI_HOST
      value: http://quays-insurance-service-ai
    - name: KUBERNETES_NAMESPACE
      value: sandbox
    - name: DB_NAME
      value: quays_insurance_db
    - name: DB_PASS
      valueFrom:
        configMapKeyRef:
          name: configs
          key: DATABASE_PASSWORD
    - name: DB_USER
      valueFrom:
        configMapKeyRef:
          name: configs
          key: DATABASE_USERNAME
    - name: DB_HOST
      valueFrom:
        configMapKeyRef:
          name: configs
          key: DATABASE_HOST
