name: investpulse-app
project: mintyn-project
namespace: production
values: |-
  fullnameOverride: investpulse-app
  image: 
    repository: mintfintech/investpulse-app:prod-app-4
  namespace: production
  containerPort: 3000
  autoscaling:
    enabled: false
  role:
    enabled: true
  ingress:
    host: investpulse
    domain: mintyn.com
  resources:
    requests:
      memory: "100Mi"
      cpu: "50m"
    limits:
      memory: "250Mi"
      cpu: "150m"
  lProbe:
    enabled: true
    path: /
    failureThreshold: 5
    periodSeconds: 5
    initialDelaySeconds: 10
  rProbe:
    enabled: false
    path: /
    failureThreshold: 5
    periodSeconds: 5
    initialDelaySeconds: 10
