name: affiliate-webapp
project: mintyn-project
namespace: production
values: |-
  fullnameOverride: affiliate-webapp
  image: 
    repository: mintfintech/mint-affiliate-app:app-1
  namespace: production
  containerPort: 80
  autoscaling:
    enabled: false
  role:
    enabled: true
  ingress:
    host: affiliate
    domain: mintyn.com
  resources:
    requests:
      memory: "25Mi"
      cpu: "10m"
    limits:
      memory: "500Mi"
      cpu: "500m"
  lProbe:
    enabled: false
    path: /
    failureThreshold: 5
    periodSeconds: 5
    initialDelaySeconds: 10
  rProbe:
    enabled: false
    path: /
    failureThreshold: 5
    periodSeconds: 5
    initialDelaySeconds: 10
