name: trade-portal
project: mintyn-project
namespace: production
values: |-
  fullnameOverride: trade-portal
  image: 
    repository: mintfintech/mintyn-trade-portal:prod-app-1
  namespace: production
  containerPort: 80
  autoscaling:
    enabled: false
  role:
    enabled: true
  ingress:
    host: tradeportal
    domain: mintyn.com
  resources:
    requests:
      memory: "10Mi"
      cpu: "10m"
    limits:
      memory: "1Gi"
      cpu: "500m"
  lProbe:
    enabled: false
    path: /
    failureThreshold: 5
    periodSeconds: 5
    initialDelaySeconds: 10
  rProbe:
    enabled: false
    path: /
    failureThreshold: 5
    periodSeconds: 5
    initialDelaySeconds: 10
