name: quays-insurance-service-ai
project: mintyn-project
namespace: production
values: |-
  fullnameOverride: quays-insurance-service-ai
  image: 
    repository: goquays/quays-insurance-service-ai:app-prod-1
  namespace: production
  containerPort: 5000
  autoscaling:
    enabled: false
  role:
    enabled: true
  ingress:
    host: ai
    domain: goquays.com
  resources:
    requests:
      memory: "350Mi"
      cpu: "200m"
    limits:
      memory: "500Mi"
      cpu: "500m"
  lProbe:
    enabled: false
    path: /health
    failureThreshold: 5
    periodSeconds: 10
    initialDelaySeconds: 60
  rProbe:
    enabled: false
    path: /health
    failureThreshold: 5
    periodSeconds: 10
    initialDelaySeconds: 60
  env:
    - name: QUAYS_INSURANCE_SERVICE_SERVICE_AI_HOST
      value: http://quays-insurance-service-ai
    - name: KUBERNETES_NAMESPACE
      value: production
    - name: DB_NAME
      value: quays_insurancedb
    - name: DB_PASS
      valueFrom:
        configMapKeyRef:
          name: configs
          key: QUAYS_DB_USER_PASSWORD
    - name: DB_USER
      valueFrom:
        configMapKeyRef:
          name: configs
          key: QUAYS_DB_USER
    - name: DB_HOST
      valueFrom:
        configMapKeyRef:
          name: configs
          key: DATABASE_HOST
