name: quays-insurance-service
project: mintyn-project
namespace: production
values: |-
  fullnameOverride: quays-insurance-service
  image: 
    repository: goquays/quays-insurance-service:app-prod-15
  namespace: production
  containerPort: 9100
  autoscaling:
    enabled: false
  role:
    enabled: true
  ingress:
    host: api
    domain: goquays.com
  resources:
    requests:
      memory: "500Mi"
      cpu: "100m"
    limits:
      memory: "1500Mi"
      cpu: "1000m"
  lProbe:
    enabled: true
    path: /actuator/health
    failureThreshold: 5
    periodSeconds: 10
    initialDelaySeconds: 60
  rProbe:
    enabled: true
    path: /actuator/health
    failureThreshold: 5
    periodSeconds: 10
    initialDelaySeconds: 60
  env:
    - name: QUAYS_INSURANCE_SERVICE_SERVICE_HOST
      value: http://quays-insurance-service
    - name: KUBERNETES_NAMESPACE
      value: production
    - name: SPRING_PROFILES_ACTIVE
      value: prod
  volumeMounts:
    - name: config
      mountPath: "/quays/config"
      readOnly: true
  volumes:
    - name: config
      configMap:
        name: quays-insurance-service
