name: quays-admin-portal
project: mintyn-project
namespace: production
values: |-
  fullnameOverride: quays-admin-portal
  image: 
    repository: goquays/quays-admin-portal:app-prod-7
  namespace: production
  containerPort: 3000
  autoscaling:
    enabled: false
  role:
    enabled: true
  ingress:
    host: admin
    domain: goquays.com
  resources:
    requests:
      memory: "50Mi"
      cpu: "20m"
    limits:
      memory: "300Mi"
      cpu: "250m"
  lProbe:
    enabled: true
    path: /
    failureThreshold: 5
    periodSeconds: 5
    initialDelaySeconds: 10
  rProbe:
    enabled: true
    path: /
    failureThreshold: 5
    periodSeconds: 5
    initialDelaySeconds: 10
