name: savings-service
project: mintyn-project
namespace: sandbox
values: |-
  fullnameOverride: savings-service
  image: 
    repository: mintfintech/mint-savings-service:prod-app-33
  namespace: production
  containerPort: 8096
  autoscaling:
    enabled: false
  role:
    enabled: true
  ingress:
    host: savings-service
    domain: mintfintech.com
  resources:
    requests:
      memory: "400Mi"
      cpu: "150m"
    limits:
      memory: "2Gi"
      cpu: "1000m"
  lProbe:
    enabled: true
    path: /actuator/health
    failureThreshold: 5
    periodSeconds: 10
    initialDelaySeconds: 60
  rProbe:
    enabled: true
    path: /actuator/health
    failureThreshold: 5
    periodSeconds: 10
    initialDelaySeconds: 60
  env:
    - name: SAVINGS_SERVICE_SERVICE_HOST
      value: http://savings-service
    - name: KUBERNETES_NAMESPACE
      value: production
    - name: SPRING_PROFILES_ACTIVE
      value: prod
    - name: KAFKA_BROKERS_URL
      valueFrom:
        configMapKeyRef:
          name: configs
          key: KAFKA_HOST
  volumeMounts:
    - name: config
      mountPath: "/config"
      readOnly: true
  volumes:
    - name: config
      configMap:
        name: savings-service
